name: CI
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - run: nx export skydive-tracker --prod
